version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./backend
    container_name: auth_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/auth_db
    volumes:
      - ./backend/app:/app/app
    restart: always

  course_service:
    build: ./backend/createCourse
    container_name: course_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/course_db
    volumes:
      - ./backend/createCourse/app:/app/app
    restart: always  

  module_lesson_service:
    build: ./backend/module_lesson
    container_name: module_lesson_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/module_db
    volumes:
      - ./backend/module_lesson:/app
      - ./backend/module_lesson/uploads:/app/uploads
    restart: always

  assessment_service:
    build: ./backend/assessments
    container_name: assessment_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8003:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/assessment_db
    volumes:
      - ./backend/assessments:/app/app
      - ./backend/assessments/uploads:/app/uploads
    restart: always  

  progress_service:
    build: ./backend/progress_service
    container_name: progress_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8004:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/progress_db
    volumes:
      - ./backend/progress_service:/app/app
    restart: always  

  marking_grading_service:
    build: ./backend/marking_grading
    container_name: marking_grading_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8005:8000"
    depends_on:
      postgres:
        condition: service_healthy
      course_service:
        condition: service_started
      assessment_service:
        condition: service_started
      progress_service:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/marking_db
    volumes:
      - ./backend/marking_grading:/app
    restart: always

volumes:
  postgres_data: